# Generated by Django 6.0.6 on 2026-07-09 20:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
