# Generated by Django 6.0.6 on 2026-08-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0003_todoitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='M', max_length=1),
        ),
    ]
